#!/usr/bin/env bash

# Grab the latest packages.
export DEBIAN_FRONTEND=noninteractive
apt-get update -q
apt-get upgrade -q -y

# Install essentials like git and the 32-bit compatiblity libraries.
apt-get install -q -y \
    subversion \
    git \
    lib32z1 \
    lib32ncurses5 \
    lib32bz2-1.0 \

# Install samba so that other machines can ping us by hostnames.
apt-get install -q -y \
    samba

# Install packages necessary for custom ruby versions.
apt-get install -q -y \
    g++ \
    libreadline6-dev \
    zlib1g-dev \
    libssl-dev \
    libyaml-dev \
    libsqlite3-dev \
    sqlite3 \
    autoconf \
    libgdbm-dev \
    libncurses5-dev \
    automake \
    libtool \
    bison \
    pkg-config \
    libffi-dev

# Install extra packages.
apt-get install -q -y \
    markdown
