#!/usr/bin/env bash

# We want to install the Ubuntu packages from the docker.io mirrors. This 
# allows us to get much more updated packages.
apt-key adv \
    --keyserver hkp://keyserver.ubuntu.com:80 \
    --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9

echo "deb https://get.docker.io/ubuntu docker main" \
    > /etc/apt/sources.list.d/docker.list

# The docker.io package has a different name so as not to interfere with the 
# official package names.
apt-get update
apt-get install -qy lxc-docker

# Set up nsenter so that we can enter running containers.
docker run -v /usr/local/bin:/target jpetazzo/nsenter

# Remove all containers.
docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)
