#!/usr/bin/env bash

# Grab the latest packages.
export DEBIAN_FRONTEND=noninteractive
apt-get update -q
apt-get upgrade -q -y

# Install essentials like git and the 32-bit compatiblity libraries.
apt-get install -q -y \
    subversion \
    git \
    lib32z1 \
    lib32ncurses5 \
    lib32bz2-1.0 \

# Install samba so that other machines can ping us by hostnames.
apt-get install -q -y \
    samba

# Install extra packages.
apt-get install -q -y \
    markdown
