#!/bin/bash

export PYTHONSTARTUP="$HOME/.pythonrc.py"

add_python_modules() {
  local dir="$1"
  shopt -s nullglob
  for d in "$dir"/*/; do
    PYTHONPATH="${PYTHONPATH:+$PYTHONPATH:}$d"
  done
  shopt -u nullglob
  export PYTHONPATH
}

# This is currently buggy. It should really just add the .python directory to
# PYTHONPATH instead of the directories inside of .python itself. Disable this
# for now.
#add_python_modules "$HOME/.python"
