# Vagrantfile API/syntax version. Don't touch unless you know what you're 
# doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "trusty-server-cloudimg-amd64-vagrant-disk1"

  config.vm.network "public_network"

  config.vm.synced_folder "salt/roots", "/srv/"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.cpus = 1
    vb.memory = 512
  end

  config.vm.provision :salt do |salt|
    salt.minion_config = "salt/minion"
    salt.run_highstate = true
    salt.log_level = "debug"
  end
end
