#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

set -x

CURRENT_HASH="$(git rev-parse HEAD)"
UPSTREAM_BRANCH="$(git rev-parse --abbrev-ref HEAD@{u})"
readonly CURRENT_BRANCH UPSTREAM_BRANCH

MERGE_BASE="$(git merge-base "${CURRENT_HASH}" "${UPSTREAM_BRANCH}")"
readonly MERGE_BASE

git checkout -p "${MERGE_BASE}" -- "$@"
