#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

set -x

if (($# != 1)); then
    echo "usage: $0 BRANCH_NAME" >&2
    exit 1
fi

readonly ORIGIN="${ORIGIN:-origin}"
readonly BRANCH_NAME="$1"

# Start from latest HEAD before creating a new branch.
git latest

CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"

git fetch "${ORIGIN}" "${BRANCH_NAME}"

git checkout -B "${BRANCH_NAME}" FETCH_HEAD
git branch -u "${CURRENT_BRANCH}"
