load("//build/lua:defs.bzl", "lua_test")

lua_test(
    name = "screen_memory_test",
    size = "small",
    src = "screen_memory_test.lua",
    deps = ["screen_memory.lua"],
)

lua_test(
    name = "keymap_labels_test",
    size = "small",
    src = "keymap_labels_test.lua",
    deps = [
        "keymap_labels.lua",
        "qmk_keycodes.lua",
    ],
)
