#!/bin/bash

function dive() {
    if type -P dive; then
        command dive "$@"
    else
        docker run --rm -it \
            -v /tmp:/tmp \
            -v /var/run/docker.sock:/var/run/docker.sock \
            wagoodman/dive:latest \
            "$@"
    fi
}
