#!/bin/bash

if type -p fd &>/dev/null; then
  export FZF_CTRL_T_COMMAND='command fd --hidden --follow --exclude ".git" .'
  export FZF_ALT_C_COMMAND='command fd --type d --hidden --follow --exclude ".git" .'
else
  # Exclude the bazel-* symlinks since they're full of files we don't really care
  # about.
  export FZF_CTRL_T_COMMAND="command find -L . -mindepth 1 \
    \\( -path '*/\\.*' -o -fstype 'sysfs' -o -fstype 'devfs' \
      -o -fstype 'devtmpfs' -o -fstype 'proc' \\) -prune \
      -o -name 'bazel-*' -prune \
      -o -type f -print \
      -o -type d -print \
      -o -type l -print 2> /dev/null | cut -b3-"

  # Exclude the bazel-* symlinks since they're full of folders we don't really
  # care about.
  export FZF_ALT_C_COMMAND="command find -L . -mindepth 1 \
    \\( -path '*/\\.*' -o -fstype 'sysfs' -o -fstype 'devfs' \
      -o -fstype 'devtmpfs' -o -fstype 'proc' \\) -prune \
      -o -name 'bazel-*' -prune \
      -o -type d -print 2> /dev/null | cut -b3-"
fi
