#!/bin/bash

set_urxvt_title() {
  local title="$1"
  if [[ -z "$title" ]]; then
    echo "Please specify a title" >&2
  else
    trap 'echo -ne "\e]0;'"$title"'\007"' DEBUG
  fi
}

set_huge_font() {
  printf '\33]50;%s\007' "xft:Terminus:pixelsize=40"
}
