#!/bin/bash

_bazel_run_complete_internal() {
  COMP_WORDS=("${COMP_WORDS[0]}" run "${COMP_WORDS[@]:1}")
  COMP_CWORD="$((COMP_CWORD + 1))"
  _bazel__complete
}

_bazel_test_complete_internal() {
  COMP_WORDS=("${COMP_WORDS[0]}" test "${COMP_WORDS[@]:1}")
  COMP_CWORD="$((COMP_CWORD + 1))"
  _bazel__complete
}

# Add some bazel wrappers to the completion as well.
if declare -f _bazel__complete > /dev/null; then
  complete -F _bazel_test_complete_internal -o nospace "itest.py"
fi
